name: Update All Stars history K8s stats

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.1"

      - name: Install dependencies
        run: go get .

      - name: Run
        working-directory: ./all-stars-history-k8s
        run: go run main.go
        env:
          PAT: ${{ secrets.PAT }}

      - name: Push generated csv files to the repo
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: Archive csv results
        uses: actions/upload-artifact@v3
        with:
          name: generated-stats-csv
          path: ./all-stars-history-k8s/*.csv
