name: Update CNCF stats

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go get .

      - name: Run
        run: go run ./cncf/main.go
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive csv results
        uses: actions/upload-artifact@v3
        with:
          name: generated-stats-csv
          path: /*.csv
