name: Update Example stats

on:
  schedule:
    - cron: "0 0 * * *" # runs at 00:00 UTC everyday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Install dependencies
        run: go get .

      - name: Run
        working-directory: ./example
        run: go run main.go
        env:
          PAT: ${{ secrets.PAT }}
          FILE_SUFFIX: "latest"

      - name: Push generated csv files to the repo
        uses: stefanzweifel/git-auto-commit-action@v5

      - name: Archive csv results
        uses: actions/upload-artifact@v4
        with:
          name: generated-stats-csv
          path: ./example/*.csv
