name: Update CNCF stats

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go get .

      - name: Run
        working-directory: ./cncf
        run: go run main.go
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
          FILE_SUFFIX: "latest"

      - name: Push generated csv files to the repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "*.csv"
          disable_globbing: true

      - name: Archive csv results
        uses: actions/upload-artifact@v3
        with:
          name: generated-stats-csv
          path: ./cncf/*.csv
